### ISSUE TITLE
Adonis isn't loading no more

### ISSUE THREAD

**Issue by FuhrerDox** [Epix-Incorporated/Adonis#1234]
- I was updating normally on studio and now adonis is completely gone.
- Adonis loading.
- Adonis not loading.
- I can't use Adonis anymore maybe?

**Comment by WalkerOfBacon** [comment]
Are you using nightly or main adonis

**Comment by FuhrerDox** [comment]
> Are you using nightly or main adonis

I'm using the Loader that I used to use by Adonis Admin Loader [Epix Incorporated]

https://create.roblox.com/marketplace/asset/7510622625/Adonis-Admin-Loader-Epix-Incorporated

It used to create the RemoteEvent now it doesn't anymore, I didn't touch anything literally, and went to all my games that has adonis on it and they all have the same problem, it literally used to work fine 30 minutes ago, I don't know what happened. Try it by yourself in Studio.

**Comment by moo1210** [comment]
> It used to create the RemoteEvent now it doesn't anymore

the what..? adonis's stable main module hasn't been updated for weeks, if you're using the stable channel of Adonis. you'll need to provide error logs as well.

**Comment by WalkerOfBacon** [comment]
> the what..? adonis's stable main module hasn't been updated for weeks, if you're using the stable channel of Adonis. you'll need to provide error logs as well.

According to him adonis completely breaks when its loading

Even when creating a whole new game

**Comment by moo1210** [comment]
If anyone else comes across this issue, it appears that Roblox is doing A/B testing on preventing to use require() with asset ids, which prevents Adonis from completely loading. This is a very small-scale rollout at this time and isn't widespread. **This isn't something we can resolve, it's a Roblox problem**, as far as we know.

I hope to have more details soon, because in the past they made it pretty clear this is *not* the path they would take, and commonly used module IDs (Adonis, F3X, other admin systems, etc.) would be exempt from the developer marketplace changes.

**Comment by moo1210** [comment]
Those issues _weren't_ related, see a log from a user's report:
![image](https://github.com/Epix-Incorporated/Adonis/assets/27241938/c004962f-9c05-4259-8565-c8221b374f55)

However, #1238 (also merged) should likely resolve this issue instead. (See: `FFlagDestroyedModuleRequireWarning` (`require() should not be called on a destroyed ModuleScript, this will become an error in the future`), `FFlagDestroyedModuleRequireReport` (or Error), or literally any engineer who knows that a Lua VM doesn't auto-ban you on Roblox, etc.)

**Comment by ccuser44** [comment]
> Those issues _weren't_ related, see a log from a user's report:

I'm pretty sure they are though. Just because F3X makes errors in the output doesn't mean that F3X is the cause.
I firmly believe the reason is [MessagingService:SubscribeAsync](https://robloxapi.github.io/ref/class/MessagingService.html#member-SubscribeAsync) yielding for ever in CrossServer.lua.
Your screenshot seems to show the same exact thing besides the F3X errors. That is, first an adonis loading ... message is generated, then a require alert and a Roblox stack trace is generated. But then after that ... nothing.
It seems to indicate some part of Adonis failed to load or more likely is yielding. Exactly what the issue was at least with Adonis not loading in studio.

![image](https://github.com/Epix-Incorporated/Adonis/assets/68124053/793631c9-86bf-4bb4-a264-96f7b83bce4f)
![image](https://github.com/Epix-Incorporated/Adonis/assets/68124053/31949425-7459-4adf-a709-6fce7289cc6b)
![image](https://github.com/Epix-Incorporated/Adonis/assets/68124053/606cfe1a-cbf8-416a-a28d-2226627e072a)

**Comment by moo1210** [comment]
> I'm pretty sure they are though. Just because F3X makes errors in the output doesn't mean that F3X is the cause.

??? where did I ever say anything about F3X in that message, lol..? those screenshots are completely different than the ones in the PR. I would agree with *those* screenshots provided, but we were having issues with users loading Adonis outside of studio.

**Comment by ccuser44** [comment]
> > I'm pretty sure they are though. Just because F3X makes errors in the output doesn't mean that F3X is the cause.
> 
> ??? where did I ever say anything about F3X in that message, lol..? those screenshots are completely different than the ones in the PR. I would agree with _those_ screenshots provided, but we were having issues with users loading Adonis outside of studio.

Oh I thought it was about studio. I wonder if it still had something to do with MessagingService or datastores?
