### ISSUE TITLE
Unknow Kick

### ISSUE THREAD

**Issue by The-Administrador** [Epix-Incorporated/Adonis#1462]
### Version channel

Stable (Default)

### What part of Adonis is this related to?

Anti-Exploit

### What happened?

As soon as my friend joint a game secured by Adonis he got kicked
(never worked with githup so idk if the picture works)
In case i forgot smth you can Dm me on discord (Username: neo_furry Dispaly name: TheHypnoCat

![Bild_2024-03-27_143544329](https://github.com/Epix-Incorporated/Adonis/assets/128135299/eca5f538-ed54-4bc2-94e4-60cb3de7c242)

**Comment by WalkerOfBacon** [comment]
Just turn off the adonis ac
Its not viable anyways

**Comment by ccuser44** [comment]
> Just turn off the adonis ac Its not viable anyways

This is not because of AC, this is because you were kicked from the game but either Adonis encountered lag or an error when kicking or a Roblox bug where lag or an error delayed or prevented the kick and [your client tried to send a remote event](https://github.com/Epix-Incorporated/Adonis/blob/master/MainModule/Server/Core/Process.lua#L302)

![image](https://github.com/Epix-Incorporated/Adonis/assets/68124053/915d0c86-91dd-4229-8d50-8c5f1bca4486)
