### ISSUE TITLE
Adonis - F3X Building Tools: Massless Bug

### ISSUE THREAD

**Issue by dylanjkl** [Epix-Incorporated/Adonis#1471]
### Version channel

Stable (Default)

### Loader version

Latest

### What part of Adonis is this related to?

Other

### What happened?

Building Tools does not function with a massless player, when the massless value is ticked for all descendants of a character and building tools are equipped (currently building tools has massless disabled and cancollide enabled) the players model is randomly teleported due to the weight of the tool.

Solution:
Enable Massless for Building Tools
Disable Cancollide for Building Tools

These changes make no difference to gameplay directly and don't break anything; they are realistically an improvement to gameplay overall and fix the niche bug with massless characters.

### Device

Windows

**Comment by KittyTheDeveloper** [comment]
i could actually do this.

**Comment by Dimenpsyonal** [comment]
We can't edit Building Tools as we just get the model from F3X

**Comment by ccuser44** [comment]
Are you sure you aren't talking about R6 characters because R6 characters are locked by Roblox.
If this affects R15 then it may be an F3X bug.

Adonis used to be able to update F3X but because of Roblox banning for no reason we no longer cant. Test if same bug exists in F3X and make a bug report to [their repo](https://github.com/F3XTeam/RBX-Building-Tools)
