### ISSUE TITLE
Prefix will not change when changed via ingame settings ui

### ISSUE THREAD

**Issue by EasternBloxxer** [Epix-Incorporated/Adonis#1540]
### Version channel

Stable (Default)

### Loader version

Latest

### What part of Adonis is this related to?

ingame settings UI

This only happens after a rejoin
![RobloxStudioBeta_GBmQJUe08q](https://github.com/Epix-Incorporated/Adonis/assets/54174182/2495275b-ad5f-4415-b448-1eb43c0ba536)

**Comment by Dimenpsyonal** [comment]
Interesting

**Comment by Sqikerz** [comment]
When you use the UI to change any of the prefix settings, it loops through all commands and manually changes the prefix. It also saves the prefix setting and that is working perfectly

issue is that commands are directly loaded with ``Settings.Prefix`` and don't even check if the "Setting" (from remote.get) is different from ``Settings.Prefix``

https://github.com/Epix-Incorporated/Adonis/blob/5fd733e50e17d398642c2aaa2537e51a865b223e/MainModule/Server/Core/Remote.lua#L840


ps: I have no idea on how I you would implement this on due to the "load" order & I can't really trace back the files
